7/21/2025
<img width="681" height="576" alt="image" src="https://github.com/user-attachments/assets/e033ec09-83e9-459f-a2b3-d93511233366" />
This is the sk4etch of the eltronics
<img width="1378" height="1039" alt="image" src="https://github.com/user-attachments/assets/fa75952e-ce2e-450e-aec3-98b3bccbb663" />
took measurments and extruded to scale. The L298n H bridge has space for its these
<img width="758" height="673" alt="image" src="https://github.com/user-attachments/assets/574dd1d8-4a12-47d9-a32e-d0ec3c586b8a" />
<img width="797" height="805" alt="image" src="https://github.com/user-attachments/assets/7449706f-a6bb-4184-b8f3-33c48ebf2da2" />
rotating platforms
Middle holes:
<img width="475" height="376" alt="image" src="https://github.com/user-attachments/assets/96f6fb3b-aa55-48dc-81d4-2fd0fcee37dc" />
Time spent; 5h
Final Eletrocal Component Mount:
<img width="861" height="585" alt="image" src="https://github.com/user-attachments/assets/c863f513-f2d2-4156-aeac-9895fa3361f1" />
for the wheels, Ill extude a circle in the middle of oen of them for the cat:
<img width="770" height="845" alt="image" src="https://github.com/user-attachments/assets/5c2101e5-ee6c-42de-a9f2-8f6f916a292a" />
Also if I dont it might spin off :( 
<img width="643" height="433" alt="image" src="https://github.com/user-attachments/assets/639556d8-18ba-4739-b017-b72c434da297" />
7/22/2025

Rotating platforms:
<img width="1062" height="739" alt="image" src="https://github.com/user-attachments/assets/8bf5a0f3-39f4-438a-85b1-ceb4d5e0e463" />
Assembly:
<img width="1404" height="928" alt="image" src="https://github.com/user-attachments/assets/a5fb50f3-7028-4a45-bc44-f274d637174f" />

My mistake was in the assumption that the cat is small enough for the plate. I must first scale it down.  
I took the two furtheest points.

<img width="1260" height="1131" alt="image" src="https://github.com/user-attachments/assets/e129c70c-1aaa-4ce5-83b6-1772885bc56f" />
just to save room for error, ill round to 80. The diameter of my playform is 58.53149. The scale factor is 58.53149/80.

<img width="1665" height="736" alt="image" src="https://github.com/user-attachments/assets/dfdfbf0c-6a0c-4ae7-b12a-4e167f06bdb3" /> seems to fit perfectly :D 
now, I made the middle peg based off this hole
<img width="1414" height="803" alt="image" src="https://github.com/user-attachments/assets/4f325ce1-217a-4fac-8ce5-624cff7c6764" />
final assembly:
<img width="1453" height="948" alt="image" src="https://github.com/user-attachments/assets/d1a8cbaa-ec9d-4259-9123-a051423633df" />
<img width="1187" height="819" alt="image" src="https://github.com/user-attachments/assets/5a858197-1478-4de2-a24e-6f3cbe98307a" />

<img width="1190" height="996" alt="image" src="https://github.com/user-attachments/assets/62da032d-ffb0-4ff3-aa25-a08a1423b2d7" />

Time spent: 3 hours
